// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdQDenyKiL8FkbYr66khjbYYBSslwM3UA',
    appId: '1:107186198982:web:3f9b3e8a771d683f14bac7',
    messagingSenderId: '107186198982',
    projectId: 'mehenty-app',
    authDomain: 'mehenty-app.firebaseapp.com',
    storageBucket: 'mehenty-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Fz4L752Nx4N_iXwo5qiZVeUzH0Rfyz4',
    appId: '1:107186198982:android:99852f5a709d29f514bac7',
    messagingSenderId: '107186198982',
    projectId: 'mehenty-app',
    storageBucket: 'mehenty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-XK3mLeHIrEbjNigEtFuJ_GpTsuimfzs',
    appId: '1:107186198982:ios:0a65488d670d1b3c14bac7',
    messagingSenderId: '107186198982',
    projectId: 'mehenty-app',
    storageBucket: 'mehenty-app.appspot.com',
    iosBundleId: 'com.example.mehentyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-XK3mLeHIrEbjNigEtFuJ_GpTsuimfzs',
    appId: '1:107186198982:ios:d0a89a2b4f0e17b614bac7',
    messagingSenderId: '107186198982',
    projectId: 'mehenty-app',
    storageBucket: 'mehenty-app.appspot.com',
    iosBundleId: 'com.example.mehentyApp.RunnerTests',
  );
}
